config/routes.rb
Rails.application.routes.draw do
    root 'home#index'
    get 'home/index'

    # devise_for :users
    devise_for :users, skip: [:registrations], controllers: {passwords: 'passwords'}

    resources :users do
        get :password_edit, on: :member
        put :password_update, on: :member
    end

    resources :posts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
    has_many :post_items, -> {order(position: :asc)}, dependent: :destroy
    belongs_to :user, optional: true, required: false
    accepts_nested_attributes_for :post_items, allow_destroy: true
    mount_uploader :image, ImageUploader
end

app/models/post_item.rb
class PostItem < ApplicationRecord
    belongs_to :post, optional: true
    mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :posts
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  mount_uploader :image, ImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @posts = Post.all
    unless params[:search].blank?
        @posts = @posts.search(params[:search])
    end
  end
end

app/controllers/passwords_controller.rb
class PasswordsController < Devise::PasswordsController

end

app/controllers/post_itmes_controller.rb
class PostItmesController < ApplicationController

    def destroy
        @post = Post.find(params[:post_id])
        @postItem = @post.post_items.find(params[:id])
        @postItem.destroy
        redirect_to edit_post_path(params[:post_id])
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :set_post, only: [:show, :edit, :update, :destroy]

    # GET /posts
    # GET /posts.json
    def index
        @page = Post.page(params[:page]).per(3)
        @posts = Post.order(created_at: :desc).page(@page.current_page).per(@page.limit_value)
    end

    # GET /posts/1
    # GET /posts/1.json
    def show

    end

    # GET /posts/new
    def new
        @post = Post.new
    end

    # GET /posts/1/edit
    def edit
    end

    # POST /posts
    # POST /posts.json
    def create
        @post = Post.new(post_params)
        respond_to do |format|
            if @post.save
                format.html {redirect_to @post, notice: '질문이 등록되었습니다.'}
                format.json {render :show, status: :created, location: @post}
            else
                format.html {render :new}
                format.json {render json: @post.errors, status: :unprocessable_entity}
            end
        end
    end

    # PATCH/PUT /posts/1
    # PATCH/PUT /posts/1.json
    def update
        respond_to do |format|
            updateparams = post_update_params
            if @post.update(updateparams)
                format.html {redirect_to @post, notice: '질문이 수정되었습니다'}
                format.json {render :show, status: :ok, location: @post}
            else
                format.html {render :edit}
                format.json {render json: @post.errors, status: :unprocessable_entity}
            end
        end
    end

    # DELETE /posts/1
    # DELETE /posts/1.json
    def destroy
        @post.destroy
        respond_to do |format|
            format.html {redirect_to home_index_path, notice: '질문이 삭제되었습니다.'}
            format.json {head :no_content}
        end
    end

    private

    def set_post
        @post = Post.find(params[:id]) if params[:id].present?
    end

    def post_params
        params.require(:post).permit(:title, :description, :image, post_items_attributes: [:id, :post_id, :title, :image, :description, :_destroy, :position])
    end

    def post_update_params
        params.require(:post).permit(:title, :description, :image, post_items_attributes: [:id, :post_id, :title, :image, :description, :_destroy, :position])
    end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
    # before_action :configure_sign_up_params, only: [:create]
    # before_action :configure_account_update_params, only: [:update]

    # GET /resource/sign_up
    def new
        @user = User.new
    end

    # POST /resource
    def create
        @user = User.new(users_params)
        @user.save!
    end

    # GET /resource/edit
    # def edit
    #   super
    # end

    # PUT /resource
    # def update
    #   super
    # end

    # DELETE /resource
    # def destroy
    #   super
    # end

    # GET /resource/cancel
    # Forces the session data which is usually expired after sign
    # in to be expired now. This is useful if the user wants to
    # cancel oauth signing in/up in the middle of the process,
    # removing all OAuth session data.
    # def cancel
    #   super
    # end

    # protected

    # If you have extra params to permit, append them to the sanitizer.
    # def configure_sign_up_params
    #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
    # end
    def users_params
        params.require(:user).permit(User.attribute_names + [:password, :password_confirmation])
    end

    # If you have extra params to permit, append them to the sanitizer.
    # def configure_account_update_params
    #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
    # end

    # The path used after sign up.
    # def after_sign_up_path_for(resource)
    #   super(resource)
    # end

    # The path used after sign up for inactive accounts.
    # def after_inactive_sign_up_path_for(resource)
    #   super(resource)
    # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new
        @user = User.new
    end

    def create
        @user = User.new(users_params)
        @user.save
    end

    def edit
        @user = User.find(params[:id])
    end

    def update
        @user = User.find(params[:id])
        if @user.update(users_params)
            flash[:notice] = '회원정보 수정이 완료되었습니다.'
            redirect_to edit_user_path
        end
    end

    def password_edit
        @user = User.find(params[:id])
    end

    def password_update
        @user = User.find(parmas[:id])
        if @user.update(password_params)
            flash[:success] = "비밀번호 변경이 완료되었습니다."
        end
    end

    private
    def users_params
        params.require(:user).permit(User.attribute_names + [:password, :password_confirmation])
    end

    def password_params
        params.require(:user).permit(:password, :password_confirmation)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
    def add_post_itme(name, f, association, opts={})

    end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/post_itme_helper.rb
module PostItmeHelper
end

app/helpers/post_itmes_helper.rb
module PostItmesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/home/index.html.erb
<% content_for :css_js do %>
  <%= stylesheet_link_tag 'home/index' %>
<% end %>
<div>
  <div class="post-header">
    <div class="post-title">온라인 집들이</div>
    <div class="qnq-sub-title">오늘의집 인테리어 고수들과 전문가들에게 조언을 받으세요</div>
    <div class="qnq-search">
      <%= form_tag({ action: :index }, { method: :get }) do %>
        <div class="qnq-search">
          <div class="post-search-input">
            <%= text_field_tag :search, nil, placeholder: '궁금한 것을 검색해보세요.' %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
  <div class="post-content">
    <div class="post-new-btn">
      <%= link_to "글쓰기", new_post_path %>
    </div>
    <div class="post-new-btn">
      <%= link_to "내가 쓴 글 보기", new_post_path %>
    </div>
  </div>
    <div class="post-list-item">
      <%= render 'posts/index' %>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= yield(:css_js) %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav>
      <ul class="nav-bar">
        <%= image_tag 'fulllogo-small.svg', :class => 'logo' %>
        <%= link_to "온라인집들이", home_index_path, :class => 'nav-list' %>
        <% if session[:current_user] = current_user %>
          <%= link_to "마이페이지", edit_user_path(current_user), class: 'nav-list' %>
          <%= link_to "로그아웃", destroy_user_session_path, class: 'nav-list', method: :delete %>
          <% else %>
          <%= link_to "회원가입", new_user_path, class: 'nav-list' %>
          <%= link_to "로그인", user_session_path, class: 'nav-list' %>
        <% end %>
      </ul>
    </nav>
    <div class="content">
      <%= yield %>
    </div>
  </body>
</html>

app/views/posts/_form.html.erb
<% content_for :js_css do %><%= javascript_include_tag 'application' %><% end %>
<%= form_for @post do |post_form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>
      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="post-form-cover-warpper">
    <% if @post.image.url %>
      <div class="post-form-cover" id="coverImagePreview">
        <%= image_tag 'ic-camera.svg', class: 'post-form-cover-icon' %>
        <%= image_tag(@post.image.to_s, id: 'is-cover', class: 'post-form-cover') %>
        <%= post_form.file_field :image, id: "coverUploadImage", class: "post-form-cover-file-field" %>
      </div>
    <% else %>
      <div class="post-form-cover" id="coverImagePreview">
        <%= image_tag 'ic-camera.svg', class: 'post-form-cover-icon' %>
        <%= post_form.file_field :image, id: "coverUploadImage", class: "post-form-cover-file-field" %>
      </div>
    <% end %>
    <div class="post-form-title-warpper">
      <%= post_form.text_field :title, placeholder: "제목을 입력해주세요.", class: "post-form-title"  %>
    </div>
    <div class="post-form-content-warpper">
      <%= post_form.text_area :description, placeholder: "인테리어를 하시면서 경험한 일을 소개해주세요.", class: "post-form-content-text" %>
    </div>
  </div>
  <div id="sortable">
    <%= post_form.fields_for :post_items, PostItem.new, child_index: 0 do |post_item_fields| %>
      <%= render 'post_item_form', post_item_fields: post_item_fields %>
    <% end %>
    <%= post_form.fields_for :post_items do |post_item_fields| %>
      <%= render 'post_item_form', post_item_fields: post_item_fields %>
    <% end %>
  </div>
  <div class="actions">
    <%= post_form.submit '발행하기', class: "post-new-btn" %>
  </div>
<% end %>

app/views/posts/_index.html.erb
<% if flash[:notice] %>
  <div class="notice"><%= flash[:notice] %></div>
<% end %>
  <% @posts.each do |post| %>
    <div class="post-list-content">
      <div class="post-thumb-image"><%= image_tag(post.image.to_s) %></div>
      <div>
        <div class="post-list-title"><%= post.title %></div>
        <div class="post-list-description"><%= post.description %></div>
        <div class="post-list-user-photo"></div><span class="post-list-user-name"><%= post.user_id %></span>
        <div class="post-list-btn">
          <%= link_to '보기', post %>
          <%= link_to '수정', edit_post_path(post) %>
          <%= link_to '삭제', post, method: :delete, data: { confirm: '삭제하겠습니까?' } %>
        </div>
      </div>
    </div>
  <% end %>

app/views/posts/_post_item_form.html.erb
<div class="post-item">
  <%= post_item_fields.hidden_field :position, class: 'post_item_position' %>
  <div class="add-post-item"><div class="icon"></div></div>
  <%= post_item_fields.check_box :_destroy, class: "post_item_delete" %>
  <%= post_item_fields.label :_destroy, "삭제하기", class: "post_item_delete" %>
  <div class="post-item-warpper">
    <div class="post-item-title-warpper">
      <%= post_item_fields.text_field :title, placeholder: "제목이 필요하다면 입력해주세요. (공백시 나타나지 않습니다.)", class: "post-item-title"  %>
    </div>
    <div class="post-item-content-warpper">
      <% if post_item_fields.object.id.nil? %>
        <%= image_tag 'photo.png', class: 'image-preview' %>
      <% else %>
        <%= image_tag(post_item_fields.object.image.to_s, class: 'image-preview') %>
      <% end %>
      <%= post_item_fields.file_field :image, class: "uploadPostItemImage" %>
    </div>
    <%= post_item_fields.text_area :description, placeholder: "이미지에 대한 설명을 입력해주세요.", class: "post-item-content-text" %>
  </div>
</div>

app/views/posts/edit.html.erb
<h1 class="post-show-title">온라인집들이 수정하기</h1>
<div class="post-warpper">
  <%= render 'form', post: @post %>
  <div class="post-show-btn">
    <%= link_to '보기', @post %>
    <%= link_to '목록보기', home_index_path %>
  </div>
</div>

app/views/posts/index.html.erb
<p class="notice"><%= notice %></p>
<table>
  <thead>
    <tr>
      <th>제목</th>
      <th>내용</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.description %></td>
        <td><%= link_to '보기', post %></td>
        <td><%= link_to '수정', edit_post_path(post) %></td>
        <td><%= link_to '삭제', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/posts/new.html.erb
<h1 class="title"></h1>
<p class="post-sub-title"></p>
<div class="post-warpper">
  <%= render 'form', post: @post %>
</div>

<!--<div class="post-show-btn">-->
  <%#= link_to '뒤로가기', home_index_path %>
<!--</div>-->

app/views/posts/show.html.erb
<% if flash[:notice] %>
  <div class="notice"><%= flash[:notice] %></div>
<% end %>

<div class="post-warpper">
  <p class="post-show-title"><%= @post.title %></p>
  <div class="post-show-content-warpper">
    <%= image_tag(@post.image.to_s) %>
    <div class="post-show-content-description">
      <%= @post.description %>
    </div>

    <% @post.post_items.each do |post_item| %>
      <div class="post-show-item-warpper">
        <div class="post-show-item-title">
          <%= post_item.title %>
        </div>
        <div id="postItemImagePreview">
          <%= image_tag(post_item.image.to_s) %>
        </div>
        <div class="post-show-content-description">
          <%= post_item.description %>
        </div>
      </div>
    <% end %>
  </div>
  <div class="post-show-btn">
    <%= link_to '수정하기', edit_post_path(@post) %>
    <%= link_to '목록보기', home_index_path %>
  </div>
</div>

app/views/users/edit.html.erb
<h2 class="title">회원정보수정</h2>
<% if flash[:notice] %>
  <div class="notice"><%= flash[:notice] %></div>
<% end %>
<% if @user.image.url %>
  <div><%= image_tag(@user.image.to_s, id: 'imagePreview', class: 'user-photo') %></div>
  <% else %>
  <div class="user-photo" id="imagePreview"></div>
<% end %>

<%= form_for(@user) do |f| %>
  <div class="field">
    <%= f.label :별명, :class => 'label-title' %>
    <%= f.text_field :nickname, :class => 'field-form' %>
  </div>

  <div class="field">
    <%= f.label :이메일, :class => 'label-title' %>
    <%= f.email_field :email, autofocus: true, autocomplete: "email", :class => 'field-form' %>
  </div>

  <div class="field">
    <%= f.label :프로필이미지, :class => 'label-title' %>
    <%= f.file_field :image, :class => 'field-form', id: "uploadImage" %>
  </div>
  <div class="field">
    <%= f.label :비밀번호변경, :class => 'label-title' %>
    <%= link_to "비밀번호변경하기", password_edit_user_path, class: 'label-title' %>
  </div>

  <div class="actions">
  <%= f.submit "수정하기", class: 'btn' %>
</div>
<% end %>

app/views/users/new.html.erb
<h2 class="title">회원가입</h2>
<div class="user-photo" id="imagePreview"></div>
<%= form_for(@user) do |f| %>
  <%= f.file_field :image, id: "uploadImage" %>
  <div class="field">
    <%= f.label :이메일, :class => 'label-title' %><br />
    <%= f.email_field :email, autofocus: true, autocomplete: "email", :class => 'field-form' %>
  </div>

  <div class="field">
    <%= f.label :비밀번호, :class => 'label-title' %>
    <% if @minimum_password_length %>
      <br /><em><%= @minimum_password_length %>자이상 영문 대 소문자, 숫자, 특수문자를 사용하세요.</em>
    <% end %><br />
    <%= f.password_field :password, autocomplete: "off", :class => 'field-form' %>
  </div>

  <div class="field">
    <%= f.label :비밀번호확인, :class => 'label-title' %><br />
    <%= f.password_field :password_confirmation, autocomplete: "off", :class => 'field-form' %>
  </div>

  <div class="field">
    <%= f.label :별명, :class => 'label-title' %><br />
    <%= f.text_field :nickname, :class => 'field-form' %>
  </div>
  <div class="actions">
    <%= f.submit "회원가입하기", :class => 'btn' %>
  </div>
<% end %>

app/views/users/password_edit.html.erb
<% if flash[:notice] %>
  <div class="notice"><%= flash[:notice] %></div>
<% end %>
<div class="title">비밀번호 변경 하기</div>
  <%= form_for @user, method: 'put'  do |f| %>
  <div class="field">
    <%= f.label '새 비밀번호', :class => 'label-title' %>
<%= f.password_field :password, autocomplete: "off", :class => 'field-form' %>
<% if @minimum_password_length %>
      <br />
      <em><%= @minimum_password_length %> characters minimum</em>
<% end %>
  </div>
  <div class="field">
    <%= f.label '새 비밀번호 확인', :class => 'label-title' %>
    <%= f.password_field :password_confirmation, autocomplete: "off", :class => 'field-form' %>
  </div>

  <div class="field">
    <%= f.label '이전 비밀번호', :class => 'label-title' %>
    <%= f.password_field :current_password, autocomplete: "off", :class => 'field-form' %>
    <div class="label-sub-title">* 비밀번호 변경을 위해서 기존 비밀번호를 입력해주세요.</div>
  </div>
    <div class="actions">
      <%= f.submit "비밀번호 변경", class: 'btn' %>
    </div>
  <% end %>